// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc_kOx0jZFRRmIiOOE-xGA0n4J2d1EfME',
    appId: '1:950429051287:web:b0b323aae1cbeb5fe7fcd2',
    messagingSenderId: '950429051287',
    projectId: 'notes-application-46312',
    authDomain: 'notes-application-46312.firebaseapp.com',
    storageBucket: 'notes-application-46312.appspot.com',
    measurementId: 'G-K8Q3V2HMEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeS82Nz27-5Bq-igRxZnMPp74O55P51bs',
    appId: '1:950429051287:android:2774210168ec5aaae7fcd2',
    messagingSenderId: '950429051287',
    projectId: 'notes-application-46312',
    storageBucket: 'notes-application-46312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEc3P3915DvTM2CuN_yR9eiKa8Y5DbGNQ',
    appId: '1:950429051287:ios:f24fe5e48aa66d7de7fcd2',
    messagingSenderId: '950429051287',
    projectId: 'notes-application-46312',
    storageBucket: 'notes-application-46312.appspot.com',
    iosBundleId: 'com.example.notesApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEc3P3915DvTM2CuN_yR9eiKa8Y5DbGNQ',
    appId: '1:950429051287:ios:f24fe5e48aa66d7de7fcd2',
    messagingSenderId: '950429051287',
    projectId: 'notes-application-46312',
    storageBucket: 'notes-application-46312.appspot.com',
    iosBundleId: 'com.example.notesApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc_kOx0jZFRRmIiOOE-xGA0n4J2d1EfME',
    appId: '1:950429051287:web:4cf3323e8df198aae7fcd2',
    messagingSenderId: '950429051287',
    projectId: 'notes-application-46312',
    authDomain: 'notes-application-46312.firebaseapp.com',
    storageBucket: 'notes-application-46312.appspot.com',
    measurementId: 'G-KCLM0NY55L',
  );
}
